* 泊松分布
** 知乎
   https://www.zhihu.com/question/26441147/answer/32786384
   先说结论：泊松分布是二项分布n很大而p很小时的一种极限形式

   二项分布是说，已知某件事情发生的概率是p，那么做n次试验，事情发生的次数就服从于二项分布。

   泊松分布是指某段连续的时间内某件事情发生的次数，而且“某件事情”发生所用的时间是可以忽略的。例如，在五分钟内，电子元件遭受脉冲的次数，就服从于泊松分布。

   假如你把“连续的时间”分割成无数小份，那么每个小份之间都是相互独立的。在每个很小的时间区间内，电子元件都有可能“遭受到脉冲”或者“没有遭受到脉冲”，这就可以被认为是一个p很小的二项分布。而因为“连续的时间”被分割成无穷多份，因此n(试验次数)很大。所以，泊松分布可以认为是二项分布的一种极限形式。

   因为二项分布其实就是一个最最简单的“发生”与“不发生”的分布，它可以描述非常多的随机的自然界现象，因此其极限形式泊松分布自然也是非常有用的。

   作者：田琮
   链接：https://www.zhihu.com/question/26441147/answer/82350992
   来源：知乎
   著作权归作者所有，转载请联系作者获得授权。

   http://blog.csdn.net/u011240016/article/details/52792774

** http://www.ruanyifeng.com/blog/2015/06/poisson-distribution.html
** http://maider.blog.sohu.com/304621504.html

* 二项分布

* 指数分布
** zhihu
   https://www.zhihu.com/question/24796044/answer/32785506
   https://www.zhihu.com/question/36965252

* Gamma
  https://www.zhihu.com/question/34866983

* Beta
  https://www.zhihu.com/question/30269898

* 高斯
  https://www.zhihu.com/question/26854682

* 均匀分布

* 马尔科夫
  https://www.zhihu.com/question/20962240

* 大数定理

* 中心极限定理
  大数定理就是样本均值在总体数量趋于无穷时依概率收敛于样本均值的数学期望（可不同分布）或者总体的均值（同分布）.中心极限定理就是一般在同分布的情况下,样本值的和在总体数量趋于无穷时的极限分布近似于正态分布.

* 置信区间
  https://www.zhihu.com/question/26419030?sort=created








* Summary
  伯努利分布也就是二项分布也就是0-1分布
  把 伯努利 连续 N 次， 就变成了 二项分布， 表示的是事件发生的概率是p，连续重复 N 次， 事件发生的次数 符合 二项分布
  当N变成连续的时间的时候，就变成了泊松分布，也就是说 泊松分布 是二项分布的极限形式， 表达的意思是 连续时间内 事件发生的次数， 次数是离散的， 因为是离散随机变量
  当次数变成时间间隔，也就是连续时间内，某件事发生的平均时间间隔的分布，就是指数分布

  N由离散变极限，次数由离散变连续

  伯努利分布
  |
  |
  V
  二项分布


  泊松分布


  指数分布
